# Generated by Django 3.2.3 on 2021-06-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210604_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('looking_for_a_job', 'Ищу работу'), ('open_to_suggestions', 'Открыт к предложениям'), ('not_looking_for_a_job', 'Не ищу работу')], max_length=64)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(choices=[('junior', 'Младший (junior)'), ('middle', 'Средний (middle)'), ('senior', 'Страший (senior)')], max_length=64)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.URLField()),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='job.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.user')),
            ],
        ),
    ]
