# Generated by Django 3.2.3 on 2021-06-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_application_written_cover_letter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
