# Generated by Django 3.2.3 on 2021-06-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_delete_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=64),
        ),
    ]
