# Generated by Django 3.2.3 on 2021-06-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(choices=[('frontend', 'Фронтенд'), ('backend', 'Бэкенд'), ('gamedev', 'Геймдев'), ('devops', 'Девопс'), ('design', 'Дизайн'), ('products', 'Продукты'), ('management', 'Менеджмент'), ('testing', 'Тестирование')], on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='job.specialty'),
        ),
    ]
