# Generated by Django 3.2.3 on 2022-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_resume_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.CharField(choices=[('code.frontend', 'Frontend'), ('code.backend', 'Backend'), ('gamedev', 'Gamedev'), ('devops', 'Devops'), ('design', 'Design'), ('products', 'Products'), ('management', 'Management'), ('testing', 'Testing')], max_length=120),
        ),
    ]
